plugins {
    id 'com.android.application'
}

android {
    namespace 'com.shanib.future1200'
    compileSdk 35

    defaultConfig {
        applicationId "com.shanib.future1200"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "7.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
